name: kazahana
description: A new Flutter project.
publish_to: none
version: 1.0.0

environment:
    sdk: ">=2.18.0-272.0.dev <3.0.0"

dependencies:
    animations: ^2.0.3
    beamer: ^1.5.0
    flutter:
        sdk: flutter
    json_annotation: ^4.6.0
    path: ^1.8.2
    path_provider: ^2.0.11
    tenka:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka
    tenka_runtime:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka_runtime
    utilx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_utilx

dev_dependencies:
    build_runner: ^2.0.0
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
    json_serializable: ^6.3.1

flutter:
    uses-material-design: true
    fonts:
        - family: Inter
          fonts:
              - asset: ./assets/fonts/Inter-Regular.ttf
              - asset: ./assets/fonts/Inter-Medium.ttf
                weight: 600
              - asset: ./assets/fonts/Inter-Bold.ttf
                weight: 800
        - family: GreatVibes
          fonts:
              - asset: ./assets/fonts/GreatVibes-Regular.ttf
